import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider with ChangeNotifier {
  bool isEn = true;
  Map<String, String> textsAr = {
    '': '',
    'splash_screen_text': 'اهلا بك في مناهج',
    'start': 'أبدأ الان',
    'drawer_name': 'عالم المناهج',
    'drawer_item1': 'المناهج',
    'filter': 'الفلاتر',
    'theme': 'المظهر',
    'classes': 'الفصول',
    'setting': 'الاعدادات',
    'home': 'الصفحه الرئيسيه',
    'favorite': 'المفضله',
    'calculator': 'اله حاسبه',
    'new_app': 'التطبيقات الجديده',
    'drawer_switch_title': 'اختر لغتك',
    'drawer_switch_item1': 'الانجليزية',
    'drawer_switch_item2': 'العربية',
    'theme_appBar_title': 'نمط التطبيق',
    'theme_screen_title': 'قم بتعديل أنماط تطبيقك',
    'theme_mode_title': 'أختر مظهر لتطبيقك',
    'System_default_theme': 'مظهر الجهاز الافتراضي',
    'light_theme': 'المظهر الفاتح',
    'dark_theme': 'المظهر الداكن',
    'primary': 'أختر اللون الاساسي',
    'accent': 'أختر اللون الثانوي',
    'filters_appBar_title': 'فلاترك',
    'filters_screen_title': 'قم بتعديل فلاتر تطبيقك',
    'curricula': 'المناهج',
    'your_favorites': 'أطعمتك المفضلة',
    'pdf_viewer': 'عرض الكتاب',
    'favorite_empty': 'المفضله فارغه',
    'favorites_text':
        'لم تقم بأضافة طعام مفضل لحد الآن - قم بأضافة بعض الاطعمة!',
    'link_open_text': 'افتح الشرح',
    'link_empty' : ' لا يوجد فيديوهات شرح لمادة',
    'link_not_empty' : ' فيديوهات شرح لمادة',

    'links': 'روابط شرح',
    'cur-cu1a': 'لغة عربي الصف الاول الابتدائي',
    'cur-cu1e': 'لغة انجليزية الصف الاول الابتدائي',
    'cur-cu1k': 'اكتشف بالعربي الصف الاول الابتدائي',
    'cur-cu1ke': 'اكتشف بالانجليزي الصف الاول الابتدائي',
    'cur-cu1dm': 'دين مسيحي الصف الاول الابتدائي',
    'cur-cu1di': 'دين اسلامي الصف الاول الابتدائي',
    'cur-cu2a': 'لغة عربية الصف الثاني الابتدائي',
    'cur-cu2e': 'لغة انجليزية الصف الثاني الابتدائي',
    'cur-cu2ma': 'رياضة بالعربي الصف الثاني الابتدائي',
    'cur-cu2me': 'رياضة بالانجليزي الصف الثاني الابتدائي',
    'cur-cu2k': 'اكتشف بالعربي الصف الثاني الابتدائي',
    'cur-cu2ke': 'اكتشف بالانجليزي الصف الثاني الابتدائي',
    'cur-cu2di': 'دين اسلامي الصف الثاني الابتدائي',
    'cur-cu3a': 'لغة عربية الصف الثالث الابتدائي',
    'cur-cu3e': 'لغة انجليزية الصف الثالث الابتدائي',
    'cur-cu3ma': 'رياضة بالعربي الصف الثالث الابتدائي',
    'cur-cu3me': 'رياضة بالانجليزي الصف الثالث الابتدائي',
    'cur-cu3k': 'اكتشف بالعربي الصف الثالث الابتدائي',
    'cur-cu3dm': 'دين مسيحي الصف الثالث الابتدائي',
    'cur-cu3di': 'دين اسلامي الصف الثالث الابتدائي',
    'cur-cu4a': 'لغة عربية الصف الرابع الابتدائي',
    'cur-cu4e': 'لغة انجليزية الصف الرابع الابتدائي',
    'cur-cu4ma': 'رياضة بالعربي الصف الرابع الابتدائي',
    'cur-cu4sa': 'علوم بالعربي الصف الرابع الابتدائي',
    'cur-cu4se': 'علوم بالانجليزي الصف الرابع الابتدائي',
    'cur-cu4d': 'دراسات الصف الرابع الابتدائي',
    'cur-cu4di': 'دين اسلامي الصف الرابع الابتدائي',
    'cur-cu5a': 'لغة عربية الصف الخامس الابتدائي',
    'cur-cu5e': 'لغة انجليزية الصف الخامس الابتدائي',
    'cur-cu5ma': 'رياضة بالعربي الصف الخامس الابتدائي',
    'cur-cu5me': 'رياضة بالانجليزي الصف الخامس الابتدائي',
    'cur-cu5sa': 'علوم بالعربي الصف الخامس الابتدائي',
    'cur-cu5se': 'علوم بالانجليزي الصف الخامس الابتدائي',
    'cur-cu5qa': 'قصة عربي الصف الخامس الابتدائي',
    'cur-cu5qi': 'قصة اسلامي الصف الخامس الابتدائي',
    'cur-cu6a': 'لغة عربية الصف السادس الابتدائي',
    'cur-cu6e': 'لغة انجليزية الصف السادس الابتدائي',
    'cur-cu6ma': 'رياضة بالعربي الصف السادس الابتدائي',
    'cur-cu6me': 'رياضة بالانجليزي الصف السادس الابتدائي',
    'cur-cu6sa': 'علوم بالعربي الصف السادس الابتدائي',
    'cur-cu6d': 'دراسات الصف السادس الابتدائي',
    'cur-cu6qa': 'قصة عربي الصف السادس الابتدائي',
    'cur-cu6qi': 'قصة اسلامي الصف السادس الابتدائي',
    'cla-ca1': 'الصف الاول الابتدائي عربي',
    'cla-ca2': 'الصف الثاني الابتدائي عربي',
    'cla-ca3': 'الصف الثالث الابتدائي عربي',
    'cla-ca4': 'الصف الرابع الابتدائي عربي',
    'cla-ca5': 'الصف الخامس الابتدائي عربي',
    'cla-ca6': 'الصف السادس الابتدائي عربي',
    'cla-cl1': 'الصف الاول الابتدائي لغات',
    'cla-cl2': 'الصف الثاني الابتدائي لغات',
    'cla-cl3': 'الصف الثالث الابتدائي لغات',
    'cla-cl4': 'الصف الرابع الابتدائي لغات',
    'cla-cl5': 'الصف الخامس الابتدائي لغات',
    'cla-cl6': 'الصف السادس الابتدائي لغات',
    'classesOfSchool.firstGrade': 'الصف الاول',
    'classesOfSchool.secondGrade': 'الصف الثاني',
    'classesOfSchool.thirdGrade': 'الصف الثالث',
    'classesOfSchool.fourthGrade': 'الصف الرابع',
    'classesOfSchool.fifthGrade': 'الصف الخامس',
    'classesOfSchool.sixthGrade': 'الصف السادس',
    'curriculaOfSchool.arabic': 'لغه عربية',
    'curriculaOfSchool.english': 'لغه انجليزيه',
    'curriculaOfSchool.mathInArabic': 'رياضيات بالعربي',
    'curriculaOfSchool.mathInEnglish': 'رياضيات بالانجايزي',
    'curriculaOfSchool.actashfInArabic': 'اكتشف بالعربي',
    'curriculaOfSchool.actashfInEnglish': 'اكتشف بالانجليزي',
    'curriculaOfSchool.masehy': 'دين مسيحي',
    'curriculaOfSchool.moslim': 'دين اسلامي',
    'curriculaOfSchool.scienceInArabic': 'علوم بالعربي',
    'curriculaOfSchool.scienceInEnglish': 'علوم بالانجليزي',
    'curriculaOfSchool.socialStudies': 'درسات اجتماعيه',
    'curriculaOfSchool.story': 'قصه عربي',
    'curriculaOfSchool.storyInIslam': 'قصه اسلاميه',
    'filter_title_arabic': 'عربي',
    'filter_title_language': 'لغات',
    'filter_sub_title_arabic': 'مناهج بالعربي',
    'filter_sub_title_language': 'مناهج بالانجليزي',
    'filter_sub_title_first': 'الصف الاول الابتدائي',
    'filter_sub_title_second': 'الصف الثاني الابتدائي',
    'filter_sub_title_third': 'الصف الثالث الابتدائي',
    'filter_sub_title_fourth': 'الصف الرابع الابتدائي',
    'filter_sub_title_fifth': 'الصف الخامس الابتدائي',
    'filter_sub_title_Sixth': 'الصف السادس الابتدائي',
  };
  Map<String, String> textsEn = {
    '': '',
    'start': 'GET STARTED',
    'drawer_name': 'Curriculum world!',
    'classes': 'The Classes',
    'filter': 'Filters',
    'theme': 'Themes',
    'setting': 'Setting',
    'home': 'Home Screen',
    'curricula': 'curricula',
    'favorite': 'Your Favorites',
    'calculator': 'Calculator',
    'new_app': 'New Apps',
    'drawer_switch_title': 'Choose your language.',
    'drawer_switch_item1': 'English',
    'drawer_switch_item2': 'Arabic',
    'theme_appBar_title': 'Your Themes',
    'theme_screen_title': 'Adjust your themes selection.',
    'theme_mode_title': 'Choose your Theme Mode',
    'System_default_theme': 'System Default Theme',
    'light_theme': 'Light Theme',
    'dark_theme': 'Dark Theme',
    'primary': 'Choose your primary color',
    'accent': 'Choose your accent color',
    'filters_appBar_title': 'Your Filters',
    'filters_screen_title': 'Adjust your curricula selection.',
    'pdf_viewer': 'Book Show',
    'favorite_empty': 'Your favorites is empty',
    'favorites_text': 'You have no favorites yet - start adding some!',
    'link_open_text': 'Open the explanation',
    'link_empty' : 'There are no videos explain to ',
    'link_not_empty' : 'Videos explain to ',

    'links': 'Links explaining',
    'cur-cu1a': 'Arabic First Grade Primary',
    'cur-cu1e': 'The first grade English',
    'cur-cu1k': 'Discover the first grade primary',
    'cur-cu1ke': 'Discover English first grade',
    'cur-cu1dm': 'Religion of Christian First Grade Primary',
    'cur-cu1di': 'First Islamic religion',
    'cur-cu2a': 'Arabic Grade Second Primary',
    'cur-cu2e': 'The second grade English',
    'cur-cu2ma': 'Mathematics in Arabic Grade Second Primary',
    'cur-cu2me': 'Mathematics English Grade Second Primary',
    'cur-cu2k': 'Discover Arabic for the second grade',
    'cur-cu2ke': 'Discover English for second grade primary',
    'cur-cu2di': 'Islamic religion for second grade primary',
    'cur-cu3a': 'Arabic language for the third grade',
    'cur-cu3e': 'English language for primary grade',
    'cur-cu3ma': 'Mathematics in Arabic for the third grade',
    'cur-cu3me': 'Mathematics in English for the third grade',
    'cur-cu3k': 'Discover Arabic for the third grade',
    'cur-cu3dm': 'A Christian religion for the third grade',
    'cur-cu3di': 'Islamic religion for the third grade',
    'cur-cu4a': 'Arabic language for the fourth grade primary',
    'cur-cu4e': 'English language for the fourth grade primary',
    'cur-cu4ma': 'Mathematics in the fourth grade primary',
    'cur-cu4sa': 'Arabic science for the fourth grade primary',
    'cur-cu4se': 'Science in English for the fourth grade',
    'cur-cu4d': 'Social studies of the fourth grade primary',
    'cur-cu4di': 'Islamic religion for the fourth grade primary',
    'cur-cu5a': 'Arabic language for primary fifth grade',
    'cur-cu5e': 'English language for primary fifth grade',
    'cur-cu5ma': 'Mathematics in Arabic for Fifth Grade',
    'cur-cu5me': 'Mathematics in English for Fifth Grade',
    'cur-cu5sa': 'Arabic Science for Fifth Grade',
    'cur-cu5se': 'English science for primary fifth grade',
    'cur-cu5qa': 'Arabic story for primary fifth grade',
    'cur-cu5qi': 'Islamic story for primary fifth grade',
    'cur-cu6a': 'Arabic language for primary grade',
    'cur-cu6e': 'English language for primary grade',
    'cur-cu6ma': 'Mathematics in Arabic for primary grade',
    'cur-cu6me': 'Mathematics in English for primary grade',
    'cur-cu6sa': 'Science in Arabic for primary grade',
    'cur-cu6d': 'Social studies for primary grade',
    'cur-cu6qa': 'Arabic story for primary grade',
    'cur-cu6qi': 'Islamic story for primary grade',
    'cla-ca1': 'First grade primary in Arabic',
    'cla-ca2': 'Second grade primary in Arabic',
    'cla-ca3': 'Third grade primary in Arabic',
    'cla-ca4': 'Fourth grade primary in Arabic',
    'cla-ca5': 'Fifth grade primary in Arabic',
    'cla-ca6': 'sixth grade primary in Arabic',
    'cla-cl1': 'First grade primary in languages',
    'cla-cl2': 'Second primary grade in languages',
    'cla-cl3': 'Third grade primary in languages',
    'cla-cl4': 'Fourth Grade Primitive in Languages',
    'cla-cl5': 'Fifth grade primary in languages',
    'cla-cl6': 'Sixth grade primary in languages',
    'classesOfSchool.firstGrade': 'First grade',
    'classesOfSchool.secondGrade': 'Second grade',
    'classesOfSchool.thirdGrade': 'Third grade',
    'classesOfSchool.fourthGrade': 'fourth grade',
    'classesOfSchool.fifthGrade': 'fifth grade',
    'classesOfSchool.sixthGrade': 'Sixth grade',
    'curriculaOfSchool.arabic': 'Arabic Language',
    'curriculaOfSchool.english': 'English Language',
    'curriculaOfSchool.mathInArabic': 'Mathematics in Arabic',
    'curriculaOfSchool.mathInEnglish': 'Mathematics in English',
    'curriculaOfSchool.actashfInArabic': 'Discover Arabic',
    'curriculaOfSchool.actashfInEnglish': 'Discover English',
    'curriculaOfSchool.masehy': 'Christian religion',
    'curriculaOfSchool.moslim': 'Islamic religion',
    'curriculaOfSchool.scienceInArabic': 'Science in Arabic ',
    'curriculaOfSchool.scienceInEnglish': 'Science in English',
    'curriculaOfSchool.socialStudies': 'Social Studies',
    'curriculaOfSchool.story': 'Arabic story',
    'curriculaOfSchool.storyInIslam': 'Islamic story',
    'filter_title_arabic': 'Arabic',
    'filter_title_language': 'Language',
    'filter_sub_title_arabic': 'Arabic Language',
    'filter_sub_title_language': 'English Language',
    'filter_sub_title_first': 'First grade primary',
    'filter_sub_title_second': 'Second grade primary',
    'filter_sub_title_third': 'Third grade primary',
    'filter_sub_title_fourth': 'Fourth grade primary',
    'filter_sub_title_fifth': 'Fifth grade primary',
    'filter_sub_title_Sixth': 'Sixth grade primary',
  };

  changeLan(bool lan) async {
    isEn = lan;
    notifyListeners();
    SharedPreferences prefs = await SharedPreferences.getInstance();
    prefs.setBool('isEn', isEn);
  }

  getLan() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    isEn = prefs.getBool('isEn') ?? true;
    notifyListeners();
  }

  Object getTexts(String txt) {
    if (isEn == true) return textsEn[txt] ?? '';
    return textsAr[txt]??'';
  }
}
